// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using tetris_api;

#nullable disable

namespace tetris_api.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20230718134622_InitialDatabase")]
    partial class InitialDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityAlwaysColumns(modelBuilder);

            modelBuilder.Entity("tetris_api.User", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id");

                NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(
                    b.Property<int>("Id"));

                b.Property<string>("HashedPassword")
                    .HasColumnType("text")
                    .HasColumnName("hashed_password");

                b.Property<int>("UserID").HasColumnType("integer").HasColumnName(
                    "user_id");

                b.Property<string>("Username")
                    .HasColumnType("text")
                    .HasColumnName("username");

                b.HasKey("Id").HasName("pk_users");

                b.ToTable("users", (string)null);
            });
#pragma warning restore 612, 618
        }
    }
}
